language: python
python:
  - 3.9

services:
  - docker

before_install:
  - docker build -f Dockerfile -t python-stats-calc .
  - pip install -U pip
  - pip install -U unittest
  - pip install codecov

install:
  - pip install -r requirements.txt
  - pip install ".[test]" .

script: unittest

branches:
  only:
    - main