language: python
python:
  - 3.9

services:
  - docker

before_install:
  - docker build -t python-stats-calc -f Dockerfile
  - docker run -d python-stats-calc
  - docker ps -a
  - docker run python-stats-calc